CREATE TABLE IF NOT EXISTS "sagaentry"
(
    sagaId         VARCHAR(255) NOT NULL,
    revision       VARCHAR(255),
    sagaType       VARCHAR(255),
    serializedSaga bytea,
    PRIMARY KEY (sagaId)
);

CREATE TABLE IF NOT EXISTS "associationvalueentry"
(
    id               INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    associationKey   VARCHAR(255),
    associationValue VARCHAR(255),
    sagaId           VARCHAR(255),
    sagaType         VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ASSOCIATIONVALUEENTRY_INDEX_ASSOCIATION
    ON "associationvalueentry" (sagaType, associationKey, associationValue);

CREATE INDEX IF NOT EXISTS ASSOCIATIONVALUEENTRY_INDEX_SAGA
    ON "associationvalueentry" (sagaId, sagaType);


/*
 * Contains details about the state of each "token".
 *
 * A token is used by an application event processor to keep track of the events it has processed and still
 * needs to process.
 *
 * N.B. both the command side of the application (through Sagas) and query side of the application (through projections)
 * will use this table to persist tokens for their respective event processors.
 *
 * See https://apidocs.axoniq.io/4.4/org/axonframework/eventhandling/TrackingToken.html for the different
 * types of token (under the "All Known Implementing Classes" section).
 */
CREATE TABLE IF NOT EXISTS "tokenentry"  (
    processorName VARCHAR(255) NOT NULL,
    segment       INTEGER NOT NULL,
    token         bytea NULL,
    tokenType     VARCHAR(255) NULL,
    timestamp     VARCHAR(255) NULL,
    owner         VARCHAR(255) NULL,
    PRIMARY KEY (processorName,segment)
    );